<?php

namespace OBN\Api\NewsBundle\Repository;

/**
 * NewsRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRateRepository extends \Doctrine\ORM\EntityRepository
{
}
