<?php

namespace OBN\Api\NewsBundle\Repository;

/**
 * NewsLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
