<?php

namespace OBN\Api\MemberBundle\Repository;

/**
 * MemberCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
