<?php

namespace OBN\Api\CategoryBundle\Repository;

/**
 * CategoryMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
