OBN\Api\NewsBundle\Entity\NewsMedia:
    type: entity
    table: null
    repositoryClass: OBN\Api\NewsBundle\Repository\NewsMediaRepository
    entityListeners:
          OBN\Api\NewsBundle\EntityListener\NewsMediaListener:
            preRemove: [ preRemove ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        uid:
            type: guid
        pathKey:
            type: string
            length: 255
        mediaType:
            type: MediaType
            nullable: true
        identification:
            type: string
            length: 255
        fileExtension:
            type: string
            length: 4
            column: file_extention
        fileSize:
            type: integer
            column: FileSize
        createdAt:
            type: datetime
        enabled:
            type: boolean
        orderBy:
            type: integer
        effect:
            type: MediaEffect
            nullable: true
        rotate:
            type: MediaRotation
            options:
                default: 0
        isPrimary:
            type: boolean
        xPosition:
            type: MediaXposition
            nullable: true
            options:
                default: 'center'
        yPosition:
            type: MediaYposition
            nullable: true
            options:
                default: 'center'
        mediaMimeType:
            type: MediaMimeType
            nullable: true
        mediaProvider:
            type: MediaProvider
            nullable: true
        awsJobId:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    manyToOne:
        news:
            targetEntity: OBN\Api\NewsBundle\Entity\News
            inversedBy: medias