OBN\Api\NewsBundle\Entity\NewsRate:
    type: entity
    table: null
    repositoryClass: OBN\Api\NewsBundle\Repository\NewsRateRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        rate:
            type: integer
        dateRate:
            type: datetime
            column: dateRate
        enabled:
            type: boolean

    lifecycleCallbacks: {  }
    manyToOne:
        news:
            targetEntity: OBN\Api\NewsBundle\Entity\News
            inversedBy: rates
        member:
            targetEntity: OBN\Api\MemberBundle\Entity\Member
            inversedBy: newsRate
            joinColumn:
                nullable: false
        category:
            targetEntity: OBN\Api\CategoryBundle\Entity\Category
