OBN\Api\NewsBundle\Entity\News:
    type: entity
    table: null
    repositoryClass: OBN\Api\NewsBundle\Repository\NewsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        uid:
            type: guid
        type:
            type: object
        status:
            type: object
        title:
            type: string
            length: 255
        content:
            type: string
            length: 255
        publicPath:
            type: string
            length: 255
        createdAt:
            type: datetime
        enabled:
            type: boolean
        canBeRated:
            type: boolean
        stared:
            type: boolean
    lifecycleCallbacks: {  }
    oneToMany:
        links:
            targetEntity: OBN\Api\NewsBundle\Entity\NewsLink
            orphanRemoval: true
            mappedBy: news
            cascade: [persist, remove]
        medias:
            targetEntity: OBN\Api\NewsBundle\Entity\NewsMedia
            orphanRemoval: true
            mappedBy: news
            cascade: [persist, remove]
            orderBy:
                orderBy: ASC
        rates:
            targetEntity: OBN\Api\NewsBundle\Entity\NewsRate
            orphanRemoval: true
            mappedBy: news
            cascade: [persist, remove]
    manyToOne:
        category:
            targetEntity: OBN\Api\CategoryBundle\Entity\Category
        member:
            targetEntity: OBN\Api\MemberBundle\Entity\Member
            inversedBy: news